#cloud-config
users:
  - default
  - name: ubuntu
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: users, admin
    shell: /bin/bash

packages:
  - git
  - python3-dev
  - python3.10-dev
  - python3-setuptools
  - python3-pip
  - python3-distutils
  - python3.10-venv
  - software-properties-common
  - libmysqlclient-dev
  - redis-server
  - xvfb
  - libfontconfig
  - wkhtmltopdf
  - curl

package_update: true
package_upgrade: true

runcmd:
  - curl -s https://deb.nodesource.com/setup_16.x | sudo bash
  - curl -LsS -O https://downloads.mariadb.com/MariaDB/mariadb_repo_setup
  - chmod +x mariadb_repo_setup
  - mariadb_repo_setup --mariadb-server-version=10.6
  - apt update
  - apt install nodejs -y
  - apt install mariadb-server mariadb-client -y
  - npm install -g yarn
  - echo -e  "\n[mysqld]\ncharacter-set-client-handshake = FALSE\ncharacter-set-server = utf8mb4\ncollation-server = utf8mb4_unicode_ci\n\n[mysql]\ndefault-character-set = utf8mb4">>/etc/mysql/my.cnf
  - systemctl start mariadb

final_message: "Environment is ready in $UPTIME seconds"
